version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install-packages
          command: cd lib && npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: cd .. && npm run semantic-release || true
