version: 2
jobs:
  build: 
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install-packages
          command: cd lib && npm install
      - run:
          name: build
          command: npm run build
          
