version: 2
jobs:
  build: 
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: install-packages
          command: npm install
      - run:
          name: build
          command: npm run build
          
