version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:12.16.1'
    steps:
      - checkout
      - run:
          name: install-dev-packages
          command: npm install
      - run:
          name: install-lib-packages
          command: cd lib && npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run semantic-release || true
